site_name: Compliance Customer Experience Engineering (CxE)
site_url: https://microsoft.github.io/ComplianceCxE
repo_url: https://github.com/microsoft/ComplianceCxE
repo_name: microsoft/ComplianceCxE
edit_uri: https://github.com/microsoft/ComplianceCxE/edit/public/docs
nav:
    - OSS: 
      - One Stop Shop: index.md
      - Advanced Audit: resources/audit.md
      - Advanced eDiscovery (AeD): resources/aed.md
      - Communication Compliance (CC): resources/cc.md
      - Compliance Manager (CM): resources/cm.md
      - Data Loss Prevention (DLP): resources/dlp.md
      - Insider Risk Management (IR): resources/ir.md
      - Microsoft Information Governance (MIG/RM): resources/mig.md
      - Microsoft Information Protection (MIP): resources/mip.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Notes from the Field:
      #- Compliance Manager: notes/cm.md
      #- Advanced eDiscovery: notes/aed.md
      #- Advanced Audit: notes/audit.md
      #- Insider Risk: notes/ir.md
      #- Communication Compliance: notes/cc.md
      - Information Governance:
        - Deep Dive into the Exchange Recoverable Items Folder: notes/mig/ri.md
      - Records Management: 
        - Annoucing Multi-Stage Public Preview: notes/mig/ms.md
      #- Information Protection: notes/mip.md
      #- Data Loss Prevention: notes/dlp.md
      - Compliance in K-12 Education: notes/ComplianceEdu.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - DAGs:
      - Getting Started: dag.md
      - Compliance Manager: dag/cm.md
      - Microsoft Compliance Configuration Analyzer (MCCA): dag/mcca.md
      - Adanced eDiscovery and Advanced Audit: dag/aed-audit.md
      - Insider Risk Management and Communication Compliance: dag/ir-cc.md
      - Microsoft Information Governance and Records Management: dag/mig-rm.md
      - Microsoft Information Protection and Data Loss Prevention: dag/mip-dlp.md
      - Resources: dag/dag-resources.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    #- PowerShell: 
      #- Compliance Manager: powershell/cm.md
      #- Advanced eDiscovery: powershell/aed.md
      #- Advanced Audit: powershell/audit.md
      #- Insider Risk: powershell/ir.md
      #- Communication Compliance: powershell/cc.md
      #- Information Governance: powershell/mig.md
      #- Records Management: powershell/rm.md
      #- Information Protection: powershell/mip.md
      #- Data Loss Prevention: powershell/dlp.md
      #- ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Playbooks:
      - Teams DLP Playbook: playbooks/teamsdlp.md
      - Exchange ETR to DLP Playbook: playbooks/etr2dlp.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - End User Training:
      - Sensitivity Labels: enduser\sensitivity.md
      - Retention Labels: enduser\retention.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Webinars:
      - Webinars: webinars.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Scenario Based Demos:
      - About the Series: sbd.md
      - Episode 1: sbd\sbd-ep1.md
      - Episode 2: sbd\sbd-ep2.md
      - Episode 3: sbd\sbd-ep3.md
      - Episode 4: sbd\sbd-ep4.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Previews:
      - Join Private Previews: previews.md
      - ðŸ’¬ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  logo: img\scm-shield.png
  favicon: img\scm-shield.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microsoft/ComplianceCxE/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MIPNews
    - icon: fontawesome/brands/yammer
      link: https://aka.ms/MIPC/AskMIPTeam
extra_css:
  - assets/extra.css
extra_javascript:
  - scripts/extlinks.js
markdown_extensions:
  - toc:
      permalink: âš“ï¸Ž
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
plugins:
  - search
copyright: <a href="https://microsoft.github.io/ComplianceCxE/privacy/">Privacy Policy</a>
