site_name: Microsoft Purview Customer Experience Engineering (CxE)
site_url: https://microsoft.github.io/ComplianceCxE
repo_url: https://github.com/microsoft/ComplianceCxE
repo_name: microsoft/ComplianceCxE
edit_uri: https://github.com/microsoft/ComplianceCxE/edit/public/docs
nav:
    - OSS: 
      - One Stop Shop: index.md
      - Audit: resources/audit.md
      - eDiscovery: resources/aed.md
      - Communication Compliance: resources/cc.md
      - Compliance Manager: resources/cm.md
      - Data Loss Prevention: resources/dlp.md
      - Insider Risk Management: resources/ir.md
      - Data Lifecycle Management/Records Management: resources/mig.md
      - Information Protection: resources/mip.md
    - Notes from the Field:
      - Getting Started: notes.md
      - IP/DLP:
        - Best Practices for Creating IP and DLP Policies: notes/mip-dlp/mip-dlp-best-practices.md
        - Preventing external sharing with DLP policy: notes/mip-dlp/DLP-policy-externalshare.md
        - Blocking upload of files with higher sensitivity label to SPO: notes/mip-dlp/SPOblockUpload.md
        - Microsoft Purview Audit (Premium) Log Activities via the O365 Management API: notes/mip-dlp/audit-log-management-activity-api.md
      - Compliance in K-12 Education: notes/ComplianceEdu.md #must remain mixed-case as file is named that way and existing links will break if changed
    - DAGs:
      - Getting Started: dag.md
      - Compliance Manager: dag/cm.md
      - Microsoft Compliance Configuration Analyzer (MCCA): dag/mcca.md
      - DLP Migration Assistant: dag/DLPMigrationAssistant.md
      - eDiscovery and Audit: dag/aed-audit.md
      - Insider Risk Management and Communication Compliance: dag/ir-cc.md
      - Data Lifecycle Management and Records Management: dag/mig-rm.md
      - Information Protection and Data Loss Prevention: dag/mip-dlp.md
      - Resources: dag/dag-resources.md
    - Playbooks:
      - Getting Started: playbooks.md
      - Information Protection:
        - üÜï Service Side Auto-labeling: playbooks/service-side-auto-labeling.md
        - Protecting Source Code Playbook: playbooks/sourceCodePlaybook.md
      - Data Loss Prevention:
        - Teams DLP Playbook: playbooks/teamsdlp.md
        - Legacy DLP Policies (ETR) to DLP Playbook: playbooks/etr2dlp.md
      - Communication Compliance:
        - Financial Services Industry Playbook: playbooks/fsicc.md

      - üí¨ Submit CxE Feedback: https://aka.ms/mipc/mipcOSS
    - Jump Starts:
      - Getting Started: jumpstarts.md
      - Data Lifecycle Management:
        - Auto-apply Labels:
          - Using KQL Exchange Workload: jumpstarts/kql-exchange.md
        - Adaptive Policy Scopes: 
          - Exchange Workload: jumpstarts/adaptive-exchange.md
    - End User Training:
      - Sensitivity Labels: enduser/sensitivity.md
      - Retention Labels: enduser/retention.md
      - DLP User Education & User Experience: enduser/dlpenduser.md
    - Webinars:
      - Webinars: webinars.md
    - Scenario Based Demos:
      - About the Series: sbd.md
      - E01 - Series Intro: sbd/sbd-ep1.md
      - E02 - Data Discovery Concept: sbd/sbd-ep2.md
      - E03 - Security vs Compliance: sbd/sbd-ep3.md
      - E04 - AIP Scanner: sbd/sbd-ep4.md
      - E05 - Sensitivity Labels: sbd/sbd-ep5.md
      - E06 - Label Behaviors: sbd/sbd-ep6.md
      - E07 - Container Labels: sbd/sbd-ep7.md
      - E08 - Client-side Autolabel: sbd/sbd-ep8.md
      - E09 - Service-side Autolabel: sbd/sbd-ep9.md
      - E10 - MEM/Intune and MIP: sbd/sbd-ep10.md
      - E11 - MEM/Intune and MIP Part 2: sbd/sbd-ep11.md
      - üÜï SBD in PDF  - Summary of SBD in pdf: sbd/SBDinPDF.md
    - Previews:
      - Join Private Previews: previews.md    
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  logo: img/scm-shield.png
  favicon: img/scm-shield.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
extra:
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microsoft/ComplianceCxE/
    - icon: fontawesome/brands/yammer
      link: https://aka.ms/MIPC/AskMIPTeam
extra_css:
  - assets/extra.css
  - assets/cookie-consent.css
extra_javascript:
  - scripts/extlinks.js
  - scripts/cookie-consent.js
  - scripts/consent-init.js
markdown_extensions:
  - toc:
      permalink: ‚öìÔ∏é
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
copyright: <a href="https://microsoft.github.io/ComplianceCxE/privacy/">üîí Privacy Policy</a> | <a href="javascript:cookieConsent.reset()">üç™ Cookie Settings</a>

